import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import HeaderTop from "@/components/HeaderTop";
import HeaderMain from "@/components/HeaderMain";
import Navbar from "@/components/Navbar";
import { Toaster } from "sonner";

import { Session, getServerSession } from "next-auth";
import { authOptions } from "@/libs/auth/auth";
import Providers from "./Providers";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import MobNavbar from "@/components/MobNavbar";
import Footer from "@/components/Footer";

const Bricolage = Bricolage_Grotesque({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session: Session | null = await getServerSession(authOptions);

    return (
        <html lang='en'>
            <Providers>
                <body className={Bricolage.className}>
                    <HeaderTop />
                    <HeaderMain />
                    <Navbar />
                    <MobNavbar />
                    {children}
                    <Toaster position='top-right' />
                    <Footer />
                </body>
            </Providers>
        </html>
    );
}
