import type { Metadata } from "next";
import { Recursive } from "next/font/google";
import "./globals.css";
import { dir } from "i18next";
import { languages, fallbackLng } from "../i18n/settings";

import HeaderTop from "@/components/HeaderTop";
import HeaderMain from "@/components/HeaderMain";
import Navbar from "@/components/Navbar";
import { Toaster } from "sonner";

import { Session, getServerSession } from "next-auth";
import { authOptions } from "@/libs/auth/auth";
import Providers from "./Providers";
import GoogleAnalytics from "@/components/GoogleAnalytics";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import MobNavbar from "@/components/MobNavbar";
import Footer from "@/components/Footer";
import CookieBanner from "@/components/CookieBanner";

const recursive = Recursive({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export async function generateStaticParams() {
    return languages.map((lng) => ({ lng }));
}

export default async function RootLayout({
    children,
    params: { lng },
}: Readonly<{
    children: React.ReactNode;
    params: {
        lng: string;
    };
}>) {
    const session: Session | null = await getServerSession(authOptions);

    return (
        <html lang={lng} dir={dir(lng)}>
            <GoogleAnalytics GA_MEASUREMENT_ID='G-xxxxxxxxxx' />
            <Providers>
                <body className={recursive.className}>
                    <HeaderTop lng={lng} />
                    <HeaderMain lng={lng} />
                    <Navbar lng={lng} />
                    <MobNavbar />
                    {children}
                    <Toaster position='top-right' />
                    <CookieBanner lng={lng} />
                    <Footer />
                </body>
            </Providers>
        </html>
    );
}
